name: Package Publish dry-run

on:
  push:
    branches: [ master ]

jobs:

  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Dry-run'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          dryRunOnly: true
          flutter: true